(defun gen-theme-vars (spec)
  (insert "* {\n")
  (dolist (s spec)
    (let ((f (car s)))
      (when-let* ((fg (face-attribute f :foreground nil t))
                  ((not (eq 'unspecified fg))))
        (insert (format "  --%s-fg: %s;\n" f fg)))
      (when-let* ((bg (face-attribute f :background nil t))
                  ((not (eq 'unspecified bg))))
        (insert (format "  --%s-bg: %s;\n" f bg)))))
  (insert "}\n\n"))

(defun gen-theme-classes (spec)
  (dolist (s spec)
    (let ((f (car s)))
      (dolist (c (cdr s))
        (insert (format "%s {\n" c))
        (insert (format "  foreground: var(--%s-fg);\n" f))
        (insert (format "  background: var(--%s-bg);\n" f))
        (insert "}\n\n")))))

(defun gen-theme (spec)
  (gen-theme-vars spec)
  (gen-theme-classes spec))

(gen-theme
 '((default)
   (error .error)
   (warning .warning)
   (success .information)
   (highlight .highlighted-text)
   (diff-added .inserted-text)
   (diff-changed .modified-text)
   (diff-removed .removed-text)))
